name: Run CLI
on:
  #push:
  #  branches: master
  schedule:
    - cron: '0 12 * * 3'
jobs:
  run_cli:
    runs-on: ubuntu-latest
    steps:
      - name: Use node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Running CLI
        shell: bash
        env:
          PSI_API_KEY: ${{ secrets.PSI_API_KEY }}
        run: npx -p webperf-psi webperf-psi-cli --u=https://mazipan.space --k="$PSI_API_KEY"
